-- Inserting sample data into PLAYER table

INSERT INTO PLAYER(PLAYER_IDENTIFIER, RANK, GAMEMODE, ROLE)
VALUES ('rebmucuc#1337', 'RADIANT', 'COMPETITIVE', 'DUELIST');

INSERT INTO PLAYER(PLAYER_IDENTIFIER, RANK, GAMEMODE, ROLE)
VALUES ('zakella#boobz', 'IMMORTAL1', 'COMPETITIVE', 'CONTROLLER');

INSERT INTO PLAYER(PLAYER_IDENTIFIER, RANK, GAMEMODE, ROLE)
VALUES ('playerTwo#1234', 'PLATINUM2', 'SPIKE_RUSH', 'DUELIST');

INSERT INTO PLAYER(PLAYER_IDENTIFIER, RANK, GAMEMODE, ROLE)
VALUES ('playerThree#5678', 'BRONZE3', 'DEATHMATCH', 'SENTINEL');

INSERT INTO PLAYER(PLAYER_IDENTIFIER, RANK, GAMEMODE, ROLE)
VALUES ('playerFour#9101', 'SILVER1', 'ESCALATION', 'CONTROLLER');
