-- Inserting sample data into PLAYER table

-- INSERT INTO PLAYER(PLAYER_IDENTIFIER, RANK, GAMEMODE, ROLE, AGENT)
-- VALUES ('rebmucuc#1337', 'RADIANT', 'COMPETITIVE', 'DUELIST', 'RAZE');

-- INSERT INTO PLAYER(PLAYER_IDENTIFIER, RANK, GAMEMODE, ROLE, AGENT)
-- VALUES ('zakella#boobz', 'IMMORTAL1', 'COMPETITIVE', 'CONTROLLER', 'OMEN');

-- INSERT INTO PLAYER(PLAYER_IDENTIFIER, RANK, GAMEMODE, ROLE, AGENT)
-- VALUES ('playerTwo#1234', 'PLATINUM2', 'SPIKERUSH', 'DUELIST', 'REYNA');

-- INSERT INTO PLAYER(PLAYER_IDENTIFIER, RANK, GAMEMODE, ROLE, AGENT)
-- VALUES ('playerThree#5678', 'BRONZE3', 'DEATHMATCH', 'SENTINEL', 'KILLJOY');

-- INSERT INTO PLAYER(PLAYER_IDENTIFIER, RANK, GAMEMODE, ROLE, AGENT)
-- VALUES ('playerFour#9101', 'SILVER1', 'ESCALATION', 'CONTROLLER', 'OMEN');

-- Inserting sample data into PLAYER table

INSERT INTO PLAYER(PLAYER_IDENTIFIER, PASSWORD, RANK, GAMEMODE, ROLE, AGENT)
VALUES ('rebmucuc#1337', 'password1', 'RADIANT', 'COMPETITIVE', 'DUELIST', 'RAZE');

INSERT INTO PLAYER(PLAYER_IDENTIFIER, PASSWORD, RANK, GAMEMODE, ROLE, AGENT)
VALUES ('zakella#boobz', 'password2', 'IMMORTAL1', 'COMPETITIVE', 'CONTROLLER', 'OMEN');

INSERT INTO PLAYER(PLAYER_IDENTIFIER, PASSWORD, RANK, GAMEMODE, ROLE, AGENT)
VALUES ('playerTwo#1234', 'password3', 'PLATINUM2', 'SPIKERUSH', 'DUELIST', 'REYNA');

INSERT INTO PLAYER(PLAYER_IDENTIFIER, PASSWORD, RANK, GAMEMODE, ROLE, AGENT)
VALUES ('playerThree#5678', 'password4', 'BRONZE3', 'DEATHMATCH', 'SENTINEL', 'KILLJOY');

INSERT INTO PLAYER(PLAYER_IDENTIFIER, PASSWORD, RANK, GAMEMODE, ROLE, AGENT)
VALUES ('playerFour#9101', 'password5', 'SILVER1', 'ESCALATION', 'CONTROLLER', 'OMEN');

