-- Inserting sample data into PLAYER table

INSERT INTO PLAYER(PLAYER_IDENTIFIER, RANK, GAMEMODE, ROLE, AGENT)
VALUES ('rebmucuc#1337', 'RADIANT', 'COMPETITIVE', 'DUELIST', 'RAZE');

INSERT INTO PLAYER(PLAYER_IDENTIFIER, RANK, GAMEMODE, ROLE, AGENT)
VALUES ('zakella#boobz', 'IMMORTAL1', 'COMPETITIVE', 'CONTROLLER', 'OMEN');

INSERT INTO PLAYER(PLAYER_IDENTIFIER, RANK, GAMEMODE, ROLE, AGENT)
VALUES ('playerTwo#1234', 'PLATINUM2', 'SPIKERUSH', 'DUELIST', 'REYNA');

INSERT INTO PLAYER(PLAYER_IDENTIFIER, RANK, GAMEMODE, ROLE, AGENT)
VALUES ('playerThree#5678', 'BRONZE3', 'DEATHMATCH', 'SENTINEL', 'KILLJOY');

INSERT INTO PLAYER(PLAYER_IDENTIFIER, RANK, GAMEMODE, ROLE, AGENT)
VALUES ('playerFour#9101', 'SILVER1', 'ESCALATION', 'CONTROLLER', 'OMEN');
