// enums.ts

export enum Agent {
    ASTRA = 'ASTRA',
    BREACH = 'BREACH',
    BRIMSTONE = 'BRIMSTONE',
    CHAMBER = 'CHAMBER',
    CYPHER = 'CYPHER',
    DEADLOCK = 'DEADLOCK',
    FADE = 'FADE',
    GEKKO = 'GEKKO',
    HARBOR = 'HARBOR',
    JETT = 'JETT',
    KAYO = 'KAYO',
    KILLJOY = 'KILLJOY',
    NEON = 'NEON',
    OMEN = 'OMEN',
    PHOENIX = 'PHOENIX',
    RAZE = 'RAZE',
    REYNA = 'REYNA',
    SAGE = 'SAGE',
    SKYE = 'SKYE',
    SOVA = 'SOVA',
    VIPER = 'VIPER',
    YORU = 'YORU',
}

export enum PlayerRank {
    IRON1 = 'IRON1',
    IRON2 = 'IRON2',
    IRON3 = 'IRON3',
    BRONZE1 = 'BRONZE1',
    BRONZE2 = 'BRONZE2',
    BRONZE3 = 'BRONZE3',
    SILVER1 = 'SILVER1',
    SILVER2 = 'SILVER2',
    SILVER3 = 'SILVER3',
    GOLD1 = 'GOLD1',
    GOLD2 = 'GOLD2',
    GOLD3 = 'GOLD3',
    PLATINUM1 = 'PLATINUM1',
    PLATINUM2 = 'PLATINUM2',
    PLATINUM3 = 'PLATINUM3',
    DIAMOND1 = 'DIAMOND1',
    DIAMOND2 = 'DIAMOND2',
    DIAMOND3 = 'DIAMOND3',
    ASCENDANT1 = 'ASCENDANT1',
    ASCENDANT2 = 'ASCENDANT2',
    ASCENDANT3 = 'ASCENDANT3',
    IMMORTAL1 = 'IMMORTAL1',
    IMMORTAL2 = 'IMMORTAL2',
    IMMORTAL3 = 'IMMORTAL3',
    RADIANT = 'RADIANT',
  }

export enum Role {
    DUELIST = 'DUELIST',
    INITIATOR = 'INITIATOR',
    CONTROLLER = 'CONTROLLER',
    SENTINEL = 'SENTINEL',
}

export enum Gamemode {
    COMPETITIVE = 'COMPETITIVE',
    UNRATED = 'UNRATED',
    SPIKERUSH = 'SPIKERUSH',
    DEATHMATCH = 'DEATHMATCH',
    ESCALATION = 'ESCALATION',
}